# Generated by Django 3.2.9 on 2021-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_content21_obj2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction_video',
            name='video',
        ),
        migrations.AddField(
            model_name='introduction_video',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
