# Generated by Django 3.2.9 on 2021-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211202_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction_video',
            name='back_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
