# Generated by Django 3.2.9 on 2021-12-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_introduction_video_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='download01_form_text',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
