# Generated by Django 3.2.9 on 2021-12-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_download01_form_text_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction_video',
            name='video_url',
            field=models.FileField(upload_to=''),
        ),
    ]
