# Generated by Django 3.2.9 on 2021-12-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_introduction_video_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction_video',
            old_name='video_url',
            new_name='video',
        ),
    ]
