# Generated by Django 3.2.9 on 2021-12-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_introduction_video_back_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call06',
            old_name='background_iamge',
            new_name='background_image',
        ),
    ]
