# Generated by Django 3.2.9 on 2021-12-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_background_iamge_call06_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
