# Generated by Django 3.2.9 on 2021-12-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_chat_id_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_id',
            name='chat_id',
            field=models.PositiveIntegerField(),
        ),
    ]
